### ISSUE TITLE
React(-Native) 테스트에 관하여..

### ISSUE THREAD

**Issue by jeonbyeongmin** [sumi-0011/took#42]
<br/>

테스트 공부는 잘돼가시나요. 학교에서 시킨다는 이유 때문에 맹목적으로 하지말고 우리가 지금 하고 있는게 대체 무엇인지 생각해보자구요.

<br/>

### 테스트를 진행하는 이유 🤔
개발자도 사람이기 때문에 실수를 합니다. 테스트는 이런 실수를 발견하고 코드가 작동하는지 확인하는데 도움이 됩니다. 물론 우리들의 프로젝트처럼 작은 프로젝트를 처음 개발할 때는 실수가 안나올 수도 있겠지요. 하지만 개발을 완료하고 새로운 기능을 추가하거나 기존 코드를 리팩토링할 때는 어떨까요? (얼마 전에 제가 전체적으로 리팩토링을 했었죠.) 

리팩토링을 하거나, 새로운 기능을 추가했을 때에도 기존 기능과 코드들을 모두 올바르게 작동해야 합니다. 그런데 이것을 어떻게 확신할 수 있을까요? 표면적으로 아무런 에러가 발생하지 않는다고 정말 아무 문제가 없는게 맞을까요? 개발자가 발견하지 못한 에러가 릴리즈 이후에 발견되면 어쩌죠? 심지어 그 에러가 원래 잘 작동하던 기능에서 발견되었다면..? 어쩌긴요. 핫픽스하느라 울며 겨자먹기로 밤을 새겠죠!

결국 테스트는 사용자 경험을 위한 것이기도 하지만 개발자를 위한 것이기도 합니다. `Lint`, `Typescript` 를 쓰는 것과 같은 맥락이지요.

<br/>

### React(-Native) 에서 테스트를 하기 전에..
앱의 테스트 가능성을 올리려면 UI는 UI 대로, 비즈니스 로직은 비즈니스 로직대로 테스트를 수행하는 것이 좋습니다. 컴포넌트에서 비즈니스 로직이나 로직들을 분리하라는 의미겠지요!!

또 테스트 방법론 중에는 많은 것들이 있는 것 같습니다. 흔히 알고 있는 TDD(테스트 주도 개발로, 실제 코드를 작성하기 전에 테스트 코드를 먼저 작성하는 방법론)도 이들 중 하나일 뿐입니다. 단지 요즘 많이 사용하는 것이고 성능이 확실하니까 많은 기업들에서 TDD를 추구하는 것이 아닐까 싶습니다. 

**하고 싶은 말은 우리가 꼭 테스트 주도 개발을 하지 않아도 된다는 것이랍니다.** 실제로 테스트가 가능한 코드를 먼저 작성하고 테스트 코드를 작성하는 것이 틀린 방법이 아닙니다! 테스트를 대체 왜 하는지 몸소 깨닫고 테스트 코드를 작성하는 것이 익숙해질 때 TDD 같은 방법을 고려하는 것이 어떨까요? 우린 아직 테스트 초보잖아요~

<br/>

### @testing-library/react-native, Jest 로 테스트하기
테스트는 기본적으로 짧고 한가지만 테스트하는 것이 이상적입니다. `it` 함수는 테스트 함수입니다. 어떻게 사용하는지 볼까요.

```js
it('given a date in the past, colorForDueDate() returns red', () => {
  expect(colorForDueDate('2000-10-20').toBe('red'));
}
```
it given a date in the past, colorForDueDate() returns red 가 하나의 문장으로 완벽한 것을 눈치채셨나요. 아래와 같은 키워드로 어떤 테스트를 수행하는지 분명하게 합시다. 

1. given : 사전 조건
2. when : 테스트 중인 함수에 의해 실행되는 특정 액션
3. then : 예상되는 결과

jest 에서 `it` 과 `test` 함수는 이름빼고 다 똑같아요. 단지 첫번째 인자에 한글을 사용할 때에는 `it` 보다는 `test` 가 더 잘 와닿는 것 같아요.

#### 단위 테스트?
단위 테스트는 개별 함수같은 코드의 가장 작은 부분을 테스트 합니다. 테스트 중인 객체에 dependency 가 있다면, mock 함수를 작성해야 할 수도 있어요. mock 함수를 사용하는 이유는 세 가지로 설명할 수 있어요.

1. 테스트가 느리고 불안정할 수 있다.
2. 해당 dependency가 항상 같은 결과를 리턴한다고 보장할 수 없다.
3. 서드파티 서비스를 현재 사용하지 못하는 상황일 수 있다.

#### 통합 테스트?
통합 테스트에서는 각 단위들이 상호 작용하는 것을 테스트해요. 즉, 각 개발 단위들이 결합되고 함께 테스트되어 예상대로 작동하는 것을 확인하는 것이지요.

#### 컴포넌트 테스트?
비즈니스 로직의 테스트 커버리지가 높고 정확하더라도, 컴포넌트 테스트가 없다면 사용자에게 의도와 다른 UI를 제공할 수도 있어요. **컴포넌트 테스트는 단위 테스트와 통합 테스트에서 사용될 수 있어요.** 우리는 컴포넌트의 어떤 것을 테스트해야 할까요?

1. 상호작용 : 사용자와 상호 작용할 때 컴포넌트가 올바르게 작동하는지 확인하기 위해 (예를 들면 사용자가 버튼을 눌렀을 때!)
2. 렌더링 : 리액트에서 사용하는 컴포넌트 렌더링이 올바른지 확인하기 위해 (예를 들면 UI에서 버튼의 모양 및 배치같은 것!)

예를 들면 onPress 리스너가 있는 버튼이 있을 때, 버튼이 올바르게 표시되고 버튼을 클릭하는 것이 컴포넌트에서 올바르게 처리되는지 테스트하는 것이지요. 아래 코드를 확인해볼까요.

```js
function GroceryShoppingList() {
  const [groceryItem, setGroceryItem] = useState('');
  const [items, setItems] = useState([]);

  const addNewItemToShoppingList = useCallback(() => {
    setItems([groceryItem, ...items]);
    setGroceryItem('');
  }, [groceryItem, items]);

  return (
    <>
      <TextInput
        value={groceryItem}
        placeholder="Enter grocery item"
        onChangeText={(text) => setGroceryItem(text)}
      />
      <Button
        title="Add the item to list"
        onPress={addNewItemToShoppingList}
      />
      {items.map((item) => (
        <Text key={item}>{item}</Text>
      ))}
    </>
  );
}
```

위 코드는 꽤 순순한 UI 컴포넌트라고 생각해요. 물론 `addNewItemToShoppingList` 와 같은 상태관리를 하는 로직이 View와 혼재되어 있지만 이 정도는 대부분의 상황에서 허용할 수 있는 수준이라고 생각해요.

자, 아무튼 우리는 위 코드에서 어떤 것을 테스트해야 할까요? **props에 어떤 것들이 들어오고, state의 값이 무엇인지 테스트하지마세요!** 이는 리팩토링으로 인해 테스트 코드가 쉽게 깨질 수 있고 다시 작성해야할 수 있어요. 결론은 UI가 잘 나타났고, 버튼을 눌렀을 때 예상되는 동작이 잘 되는지 테스트하면 됩니다!

```js
test('given empty GroceryShoppingList, user can add an item to it', () => {
  const { getByPlaceholder, getByText, getAllByText } = render(
    <GroceryShoppingList />
  );

  fireEvent.changeText(
    getByPlaceholder('Enter grocery item'),
    'banana'
  );
  fireEvent.press(getByText('Add the item to list'));

  const bananaElements = getAllByText('banana');
  expect(bananaElements).toHaveLength(1); // expect 'banana' to be on the list
});
```

이 테스트 코드는 `<GroceryShoppingList/>` 컴포넌트가 주어졌을 때 유저가 `item` 을 `list` 에 추가하는 것을 테스트 합니다. 정확하게 하나의 기능을 테스트 하는 것이죠. 이 일련의 과정을 테스트 코드로 작성해봅시다.

먼저 `fireEvent` 는 jest에서 제공하고 `changeText()` 를 이용하여 해당 부분에 Text 를 변경할 수 있습니다. 유저가 input 에 무언가 작성했다고 **가정**하는 것이죠. 그 다음 `press()` 를 이용하여 `Add the item to list` 라는 Text 를 가진 버튼을 클릭합니다. 그 다음 `getAllByText('banana')` 로 바나나라는 텍스트를 가진 모든 엘레멘츠를 가져옵시다. 만약 이것의 길이가 1이라면 `list` 에 잘 추가했다고 예상할 수 있어요.

<br/>

### 결론
제 생각에는 어떤 컴포넌트를 테스트하냐에 따라서 여러가지 테스트를 적용할 수 있을 거 같아요.
1. components : 이 디렉토리에 존재하는 컴포넌트들은 모두 View를 담당해요. 따라서 이 디렉토리는 컴포넌트 테스트, 단위 테스트, 통합 테스트를 적용합시다.
2. screens : 이 디렉토리에 존재하는 컴포넌트들은 많은 컴포넌트들이 사용되는 곳이니, 컴포넌트 테스트, 통합 테스트를 적용할 수 있을 것 같아요.
3. 비즈니스 로직 : 비즈니스 로직들은 전부 hooks로 빼서 따로 단위 테스트하는 게 좋을 거 같아요.

또 Jest 에서는 스냅샷 테스트를 제공해요. 말그대로 화면을 찍어서 개발자가 읽을 수 있는 코드로 확인할 수 있는 형태로 변환해요. 많은 글들에서 스냅샷 테스트를 권장하지 않아요. 그 이유는 다음과 같아요.

1. View가 변경되어 fail 된 것인지, 버그로 인해 fail 된 것인지 알 수 없다.
2. View가 변경되면 jest --update-snapshots 로 새로운 View 스냅샷을 업데이트 할 수 있어요. 이는 스냅샷을 업데이트하면 언제든지 스냅샷테스트가 통과될 수 있음을 의미해요.
3. 스냅샷은 이미 만들어진 UI 컴포넌트를 찍는 것이라 TDD 같은 방법론을 사용할 때에 스냅샷 테스트는 무조건 실패할 수 밖에 없어요.
4. UI는 정적이지 않아요. 자주 변경되는 UI 를 다루는 상황에서는 스냅샷 업데이트를 자주 할테고 이런 방식의 테스트는 너무 허술한거죠.

<br/>

### Source 

[react-native official docs](https://reactnative.dev/docs/testing-overview)
[스냅샷 테스트의 단점](https://velog.io/@k7120792/%EB%B2%88%EC%97%AD-%EB%A6%AC%EC%95%A1%ED%8A%B8-%EC%8A%A4%EB%83%85%EC%83%B7-%ED%85%8C%EC%8A%A4%ED%8C%85%EC%9D%98-%EB%8B%A8%EC%A0%90%EB%93%A4-o8jypesqnr)

<br/>

**Comment by BAESI** [comment]
@jeonbyeongmin  나는 우리가 작성한 테스트 케이스 1번이 사실 스냅샷 테스트로 할 꺼라고 예상했단 말이야 ? 왜냐하면 UI가 제대로 표시되냐 안돼냐의 문제라고 생각해서 그 다른 문서에서 스냅샷은 그냥 이미 작성된 코드에서 만들어지는 거 같은데 그러면 바로 통과 될것같단 말이지. 그래서 우리는 스냅샷 테스트를 진행 하지 않고 UI가 아닌 값을 제대로 불러오는지 확인하는 테스트를 진행하는 건가 ?

**Comment by jeonbyeongmin** [comment]
우선 스냅샷 테스트를 지양해야 하는 이유는 내가 source에 올린 스냅샷 테스트의 단점을 읽어보면 느낌이 올거야. 스타일만 수정해도 스냅샷 테스트는 통과하지 못하더라구.

UI가 제대로 나오는지는 해당 엘리멘트가 존재하는지 정도로만 테스트하는 게 좋을 것 같아.

또 우리가 하고 있는 컴포넌트 테스트만으로는 모든 디바이스 모든 os에서 동일하게 나온다는 보장을 할 수가 없대. 즉 UI 가 잘 렌더링 되는지, 사용자와 상호작용에 의해 실행되는 로직, 비즈니스 로직들에 초점을 맞춰서 유닛 테스트, 통합테스트를 진행하는게 어떨까하는 생각이야. 내 생각일 뿐이라서 혹시 다른 문서를 읽다가 더 좋은 생각이 생기면 말해줘

**Comment by sumi-0011** [comment]
귣잡 
명강사가 될거같네요! 👍
