### ISSUE TITLE
쓰레기통 등록 지도 수정사항

### ISSUE THREAD

**Issue by sumi-0011** [sumi-0011/took#56]
![image](https://user-images.githubusercontent.com/49177223/171080143-81ef951e-d670-4f76-9142-7a7e45dafcf2.png)

1. 누르면 자신의 위치로 돌아가는  버튼이 필요할 것 같아요. 
2. 마커를 어떻게 움직일 수 있는지 모르겠어요. (못움직이나?)

**Comment by BAESI** [comment]
1. 자신의 위치로 원복 시키는 버튼은 구현해보겠습니다.
2. 마커는 현재 맵 중앙에 고정되어있습니다. 맵을 움직이면 마커가 따라서 움직입니다.

**Comment by BAESI** [comment]
@sumi-0011 지도 움직였을 때 마커 움직이는지 확인 부탁드립니당

**Comment by sumi-0011** [comment]
> @sumi-0011 지도 움직였을 때 마커 움직이는지 확인 부탁드립니당

넹
